myproject/core/urls.py
from django.urls import path
from myproject.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('person/json/', v.person_json, name='person_json'),
    path('filter_list/', v.filter_list, name='filter_list'),
    path('filter_dropdown/', v.filter_dropdown, name='filter_dropdown'),
    path('filter_dropdown2/', v.filter_dropdown2, name='filter_dropdown2'),
    path('cities/ajax/', v.cities_ajax, name='cities_ajax'),
    path(
        'cities/choices/ajax/',
        v.cities_choices_ajax,
        name='cities_choices_ajax'
    ),
    path('districts/ajax/', v.districts_ajax, name='districts_ajax'),
    path(
        'districts/choices/ajax/',
        v.districts_choices_ajax,
        name='districts_choices_ajax'
    ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class Person(models.Model):
    name = models.CharField('nome', max_length=100)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField('telefone', max_length=15, null=True, blank=True)
    GENDER = (
        ('0', ''),
        ('man', 'homem'),
        ('woman', 'mulher'),
    )
    gender = models.CharField(
        'sexo',
        max_length=5,
        choices=GENDER,
        default='0'
    )
    district = models.ForeignKey(
        'District',
        verbose_name='bairro',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.name

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'name': self.name,
            'email': self.email,
            'phone': self.phone,
            'gender': self.get_gender_display(),
        }


class City(models.Model):
    name = models.CharField('cidade', max_length=100)
    uf = models.CharField('UF', max_length=2, choices=STATE_CHOICES)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'cidade'
        verbose_name_plural = 'cidades'


class District(models.Model):
    name = models.CharField('distrito', max_length=100)
    city = models.ForeignKey(
        'City',
        verbose_name='cidade',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'distrito'
        verbose_name_plural = 'distritos'

myproject/core/forms.py
from django import forms
from localflavor.br.br_states import STATE_CHOICES
from .models import City, District


class StateForm(forms.Form):
    state = forms.ChoiceField(
        choices=STATE_CHOICES,
        label='Estado',
        # widget=forms.Select(
        #     attrs={'class': 'form-control'}
        # )
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.none(),
        required=False
    )
    district = forms.ModelChoiceField(
        queryset=District.objects.none(),
        required=False
    )

    class Meta:
        fields = ('state', 'city', 'district')

    def __init__(self, state=None, city=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.filter(uf=state)
        if city:
            self.fields['district'].queryset = District.objects.filter(
                city=city)

myproject/core/views.py
from django.http import JsonResponse
from django.shortcuts import render
from localflavor.br.br_states import STATE_CHOICES
from .forms import StateForm
from .models import Person, City, District


def index(request):
    context = {}
    person_list = Person.objects.all()
    context['person_list'] = person_list
    return render(request, 'index.html', context)


def person_json(request):
    persons = Person.objects.all()
    data = [person.to_dict_json() for person in persons]
    response = {'data': data}
    return JsonResponse(response)


def filter_list(request):
    context = {}
    cities = City.objects.all()
    districts = District.objects.all()
    # context['states'] = STATE_CHOICES
    context['states'] = (
        ('MG', 'Minas Gerais'),
        ('PR', 'Paraná'),
        ('RJ', 'Rio de Janeiro'),
        ('SP', 'São Paulo'),
    )
    context['cities'] = cities
    context['districts'] = districts
    return render(request, 'filter_list.html', context)


def filter_dropdown(request):
    context = {}
    context['form'] = StateForm
    # Filtro
    q = request.GET.get('district')
    if q:
        q = q.replace('.', '')
        persons = Person.objects.filter(district=str(q))
        context['persons'] = persons
    return render(request, 'filter_dropdown.html', context)


def filter_dropdown2(request):
    context = {}
    state = request.GET.get('state')
    city = request.GET.get('city')
    context['form'] = StateForm(state, city)
    # Filtro
    q = request.GET.get('district')
    if q:
        q = q.replace('.', '')
        persons = Person.objects.filter(district=str(q))
        context['persons'] = persons
    return render(request, 'filter_dropdown2.html', context)


def cities_ajax(request):
    uf = request.GET.get('uf')
    cities = City.objects.filter(uf=uf)
    context = {'cities': cities}
    return render(request, 'includes/_cities.html', context)


def cities_choices_ajax(request):
    uf = request.GET.get('uf')
    cities = City.objects.filter(uf=uf)
    context = {'cities': cities}
    return render(request, 'includes/_cities_choices.html', context)


def districts_ajax(request):
    city = request.GET.get('city')
    districts = District.objects.filter(city=city)
    context = {'districts': districts}
    return render(request, 'includes/_districts.html', context)


def districts_choices_ajax(request):
    city = request.GET.get('city')
    districts = District.objects.filter(city=city)
    context = {'districts': districts}
    return render(request, 'includes/_districts_choices.html', context)

myproject/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="https://www.djangoproject.com/s/img/icon-touch.e4872c4da341.png">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

  <title>Chained Dropdown</title>

  <style>
    body {
      padding-top: 3.5rem;
    }
  </style>
</head>
<body>

    {% include "nav.html" %}

    <main role="main">

    {% block content %}{% endblock content %}

    </main>

    <footer class="container">
      <p>&copy; Company 2018</p>
    </footer>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

  {% block js %}{% endblock js %}
</body>
</html>

myproject/core/templates/filter_dropdown.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<style>
  label {
    padding: 10px;
  }
</style>

<div class="jumbotron">
  <div class="container">
    <h2>Exemplo do uso de um filtro com dropdowns dependentes.</h2>
    <p><i>Segundo choice filtrado a partir do primeiro choice.</i></p>
    <p><a href="https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html" target="_blank">How to Implement Dependent/Chained Dropdown List with Django</a></p>

    <div style="border: dashed 1px grey;">
      <form id="myForm"
            method="GET"
            class="form-inline"
            data-urlcities="{% url 'core:cities_choices_ajax' %}"
            data-urldistricts="{% url 'core:districts_choices_ajax' %}"
            >
        <div class="form-group">
          <label for="stateSelect">Estado</label>
          {% render_field form.state title="Estados" class="form-control" %}
        </div>

        <div class="form-group" style="padding:10px;">
          <label for="citySelect">Cidade</label>
          <select class="form-control" id="citySelect">
            <option>---------------------</option>
          </select>
        </div>

        <div class="form-group" style="padding:10px;">
          <label for="districtSelect">Bairro</label>
          <select class="form-control" id="districtSelect" name="district">
            <option>---------------------</option>
          </select>
        </div>

        <div class="form-group">
          <button class="btn btn-success" type="submit">Filtrar</button>
        </div>
      </form>
    </div>

  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Bairro</th>
            <th>Cidade</th>
            <th>UF</th>
          </tr>
        </thead>
        <tbody>
          {% for person in persons %}
            <tr>
              <td>{{ person.name }}</td>
              <td>{{ person.email }}</td>
              <td>{{ person.phone }}</td>
              <td>{{ person.district }}</td>
              <td>{{ person.district.city }}</td>
              <td>{{ person.district.city.uf }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}

  <script>
    $('#id_state').change(function() {
      let urlCities = $('#myForm').data('urlcities');
      let ufIdCity = $(this).val();
      // console.log(ufIdCity);
      // console.log(urlCities);

      $.ajax({
        url: urlCities,
        data: {
          uf: ufIdCity
        },
        success: function(response) {
          $('#citySelect').html(response);
          $('#districtSelect').html('<option value="">---------------------</option>');
        }
      })
    });

    $('#citySelect').change(function() {
      let urlDistricts = $('#myForm').data('urldistricts');
      let cityIdDistrict = $(this).val();
      console.log(urlDistricts);
      console.log(cityIdDistrict);

      $.ajax({
        url: urlDistricts,
        data: {
          city: cityIdDistrict
        },
        success: function(response) {
          $('#districtSelect').html(response);
        }
      })
    });
  </script>

{% endblock js %}

myproject/core/templates/filter_dropdown2.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<style>
  label {
    padding: 10px;
  }
</style>

<div class="jumbotron">
  <div class="container">
    <h2>Exemplo do uso de um filtro com dropdowns dependentes.</h2>
    <p><i>Segundo choice filtrado a partir do primeiro choice.</i></p>

    <div style="border: dashed 1px grey;">
      <form id="myForm"
            method="GET"
            class="form-inline"
            data-state="{{ request.GET.state }}"
            data-city="{{ request.GET.city }}"
            data-district="{{ request.GET.district }}"
            >
        <div class="form-group">
          <label for="stateSelect">Estado</label>
          {% render_field form.state title="Estados" class="form-control" %}
        </div>

        <div class="form-group">
          <label for="citySelect">Cidade</label>
          {% render_field form.city title="Cidades" class="form-control" %}
        </div>

        <div class="form-group">
          <label for="districtSelect">Bairro</label>
          {% render_field form.district title="Bairro" class="form-control" %}
        </div>

        <div class="form-group">
          <button id="btnSubmit" class="btn btn-success" type="submit">Filtrar</button>
        </div>
      </form>
    </div>

  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Bairro</th>
            <th>Cidade</th>
            <th>UF</th>
          </tr>
        </thead>
        <tbody>
          {% for person in persons %}
            <tr>
              <td>{{ person.name }}</td>
              <td>{{ person.email }}</td>
              <td>{{ person.phone }}</td>
              <td>{{ person.district }}</td>
              <td>{{ person.district.city }}</td>
              <td>{{ person.district.city.uf }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function() {
      let state = $('#myForm').data('state')
      let city = $('#myForm').data('city')
      let district = $('#myForm').data('district')
      if (state) {
        $('#id_state option[value='+state+']').attr('selected', 'selected');
      }
      if (city) {
        $('#id_city option[value='+city+']').attr('selected', 'selected');
      }
      if (district) {
        $('#id_district option[value='+district+']').attr('selected', 'selected');
      }
    });

    $('#id_state').on('change', function() {
      $('#btnSubmit').click();
    });

    $('#id_city').on('change', function() {
      $('#btnSubmit').click();
    });
  </script>
{% endblock js %}

myproject/core/templates/filter_list.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<style>
  label {
    padding: 10px;
  }
</style>

<div class="jumbotron">
  <div class="container">
    <h2>Exemplo de como filtrar várias listas.</h2>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col">
      <h5>Estados</h5>
      <table class="table">
        <thead>
          <tr>
            <th>Estado</th>
            <th>UF</th>
          </tr>
        </thead>
        <tbody>
          {% for state in states %}
            <tr>
              <td>
                <a href="" 
                   class="state" 
                   data-url="{% url 'core:cities_ajax' %}?uf={{ state.0 }}" 
                   data-uf="{{ state.0 }}"
                   >{{ state.1 }}</a>
              </td>
              <td>{{ state.0 }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col">
      <!-- <table class="table">
        <thead>
          <tr>
            <th>Cidade</th>
            <th>UF</th>
          </tr>
        </thead>
        <tbody>
          {% for city in cities %}
            <tr>
              <td>{{ city.name }}</td>
              <td>{{ city.uf }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table> -->
      <div class="cities">
        <h5>Cidades</h5>
        <div id="id_cities"></div>
      </div>
    </div>
    <div class="col">
      <!-- <table class="table">
        <thead>
          <tr>
            <th>Bairro</th>
            <th>Cidade</th>
            <th>UF</th>
          </tr>
        </thead>
        <tbody>
          {% for district in districts %}
            <tr>
              <td>{{ district.name }}</td>
              <td>{{ district.city }}</td>
              <td>{{ district.city.uf }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table> -->
      <div class="districts">
        <h5>Bairros</h5>
        <div id="id_districts"></div>
      </div>
    </div>
  </div>
</div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}

  <script>
    $('.state').on('click', function(event) {
      let url = $(this).data('url');
      let uf = $(this).data('uf');
      console.log(url);

      $.ajax({
        url: url,
        data: {
          uf: uf
        },
        success: function(response) {
          $('#id_cities').html(response);
          $('#id_districts').html('');
        }
      })
      event.preventDefault();
    });

    $(document).on('click', '.city', function(event) {
      let url = $(this).data('url');
      let uf = $(this).data('uf');
      console.log(url);

      $.ajax({
        url: url,
        data: {
          uf: uf
        },
        success: function(response) {
          $('#id_districts').html(response);
        }
      })
      event.preventDefault();
    });
  </script>

{% endblock js %}

myproject/core/templates/includes/_cities.html
<table class="table">
  <thead>
    <tr>
      <th>Cidade</th>
      <th>UF</th>
    </tr>
  </thead>
  <tbody>
    {% for city in cities %}
      <tr>
        <td>
          <a href="" 
             class="city" 
             data-url="{% url 'core:districts_ajax' %}?city={{ city.pk }}" 
             data-uf="{{ city.pk }}"
             >{{ city.name }}</a>
        </td>
        <td>{{ city.uf }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

myproject/core/templates/includes/_cities_choices.html
<option value="">---------------------</option>
{% for city in cities %}
  <option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

myproject/core/templates/includes/_districts.html
<table class="table">
  <thead>
    <tr>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>UF</th>
    </tr>
  </thead>
  <tbody>
    {% for district in districts %}
      <tr>
        <td>{{ district.name }}</td>
        <td>{{ district.city }}</td>
        <td>{{ district.city.uf }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

myproject/core/templates/includes/_districts_choices.html
<option value="">---------------------</option>
{% for district in districts %}
  <option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}

myproject/core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h2>Exemplo do uso de <a href="https://datatables.net/" target="_blank">DataTables</a></h2>
    <p>Exemplo do uso de DataTables com Django.</p>
    <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p> -->
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-6">
      <h2>Contatos</h2>
      <table id="myTable1" class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Gênero</th>
          </tr>
        </thead>
        <tbody>
          {% for person in person_list %}
            <tr>
              <td>{{ person.name }}</td>
              <td>{{ person.email }}</td>
              <td>{{ person.phone }}</td>
              <td>{{ person.get_gender_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <h2>Contatos via JSON</h2>
      <table id="myTable2" class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Gênero</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}

myproject/core/templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Exemplo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:filter_list' %}">Filtrando lista</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:filter_dropdown' %}">Filtrando com dropdown</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:filter_dropdown2' %}">Filtrando com dropdown com Django Forms</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>